name: CD

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenchement sur des tags correspondant à des versions (par exemple v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Deploy to production
      run: npm run deploy
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PWD: ${{ secrets.DB_PWD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        PORT_NUMBER: ${{ secrets.PORT_NUMBER }}
