name: CI

on:
  push:
    branches:
      - main  # Déclencher sur les pushs vers la branche main
  pull_request:
    branches:
      - main  # Déclencher sur les PR vers la branche main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build
